services:
    server:
        image: websocket-server:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        env_file:
            - .env
